version: '3.8'

services:
  chat_service:
    image: python:3.10-slim
    container_name: chat_service
    working_dir: /app
    environment:
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-admin123}
      DB_HOST: ${DB_HOST:-mysql_db}
    volumes:
      - "${PROJECT_ROOT}/src:/app/src"  # Always mount the source code
    command: >
      /bin/sh -c "
      pip install -r ./src/backend/lib/requirements.txt &&
      uvicorn src.backend.chat_service.chat_service:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-admin123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${DB_USER:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin123}
    volumes:
      - mysql_data:/var/lib/mysql  # Use a named volume for MySQL data

# Define the named volume
volumes:
  mysql_data:

# Define the absolute path for PROJECT_ROOT
x-environment:
  PROJECT_ROOT: ${PROJECT_ROOT}
