

services:
  chat_service:
    image: python:3.10-slim
    container_name: chat_service
    working_dir: /app
    environment:
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-admin123}
      DB_HOST: ${DB_HOST:-mysql_db}
    volumes:
      - ./db:/app/db
      - ./chat_service:/app/chat_service
      - ./lib:/app/lib
    command: >
      /bin/sh -c "
      pip install -r ./lib//requirements.txt &&
      uvicorn chat_service.chat_service:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-admin123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${DB_USER:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin123}
    ports:
      - "3306:3306"  # Only accessible within the Docker network
    volumes:
      - ./mysql_data:/var/lib/mysql  # Custom path under backend directory

volumes:
  mysql_data:
    external: true  # Not needed if using host directory