name: Docker Compose Test on PR

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the pull request code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker and Docker Compose
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker

      # Check Docker version
      - name: Check Docker version
        run: docker --version

      # Step 3: Run Docker Compose
      - name: Run docker-compose up
        working-directory: src/backend
        env:
          PROJECT_ROOT: ${{ github.workspace }}
        run: docker-compose up -d

      # View Docker logs
      - name: View Docker logs
        run: docker-compose logs

      # Step 4: Check if Ollama server is up
      - name: Check Ollama server status
        run: |
          end=$((SECONDS+180))  # Wait up to 3 minutes
          while [ $SECONDS -lt $end ]; do
            if curl -s http://localhost:11434 > /dev/null; then
              echo "Ollama server is up!"
              exit 0
            else
              echo "Waiting for Ollama server to be up..."
              sleep 5
            fi
          done
          echo "Error: Ollama server did not start within 3 minutes."
          exit 1

      # Step 5: Test if the main server is up
      - name: Test server with curl
        run: |
          end=$((SECONDS+240))  # Wait up to 4 minutes
          while [ $SECONDS -lt $end ]; do
            if curl -s http://localhost:8000 > /dev/null; then
              echo "Server is up!"
              exit 0
            else
              echo "Waiting for server to be up..."
              sleep 5
            fi
          done
          echo "Error: Server did not start within 4 minutes."
          exit 1

      # Step 6: Run Python Integration Tests
      - name: Run Python Integration Tests
        working-directory: src/backend
        env:
          PROJECT_ROOT: ${{ github.workspace }}
        run: python -m unittest discover -s ./test/IntegrationTests

      # Step 7: Shut down Docker Compose (clean up)
      - name: Docker-compose down
        working-directory: src/backend
        if: always()
        run: docker-compose down
