name: Docker Compose Integration Test on PR

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the pull request code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Start Docker Compose
      - name: Run docker-compose up
        working-directory: src/backend
        run: docker-compose up -d

      # Step 4: Verify Ollama Server is Running
      - name: Check Ollama server health
        run: |
          echo "Checking if Ollama server is up..."
          end=$((SECONDS+180)) # Wait up to 3 minutes
          while [ $SECONDS -lt $end ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:11434/)
            if [ "$response" -eq 200 ]; then
              echo "Ollama server is running!"
              exit 0
            fi
            echo "Waiting for Ollama server readiness..."
            sleep 5
          done
          echo "Error: Ollama server did not start within 3 minutes."
          exit 1

      # Step 5: Debug Ollama Server Logs
      - name: Wait for Ollama server to start
        run: |
          echo "Waiting for Ollama server to start..."
          sleep 20  # Give the container time to fully start

      - name: List all running containers
        run: docker ps

      - name: Check Ollama server logs
        run: |
          container_id=$(docker ps -q --filter "ancestor=ollama/server")
          if [ -z "$container_id" ]; then
            echo "Error: Ollama server container not found."
            exit 1
          fi
          echo "Fetching logs for container: $container_id"
          docker logs "$container_id"


      # Step 6: Pull and Verify Model
      - name: Pull and verify llama3.2:3b model
        run: |
          echo "Pulling llama3.2:3b model..."
          response=$(curl -s -w "%{http_code}" -o response_body.txt http://localhost:11434/api/pull -d '{ "name": "llama3.2:3b" }')
          http_code="${response: -3}"
          cat response_body.txt
          if [ "$http_code" -ne 200 ]; then
            echo "Error: Failed to pull model. HTTP Code: $http_code"
            exit 1
          fi

          echo "Checking if llama3.2:3b model is loaded..."
          for i in {1..10}; do
            models=$(curl -s http://localhost:11434/api/models)
            echo "Available models: $models"
            if echo "$models" | grep -q "llama3.2:3b"; then
              echo "Model llama3.2:3b successfully loaded."
              exit 0
            fi
            echo "Model not loaded yet. Retrying in 15 seconds..."
            sleep 15
          done

          echo "Error: Model llama3.2:3b did not load."
          exit 1

      # Step 7: Test AI Responses
      - name: Test AI Responses
        run: |
          echo "Testing AI response..."
          response=$(curl -s -w "%{http_code}" -o response_body.txt http://localhost:11434/api/generate -d '{
            "model": "llama3.2:3b",
            "prompt": "Is the sky blue? Answer True or False.",
            "stream": false
          }')
          http_code="${response: -3}"
          body=$(cat response_body.txt)

          echo "HTTP Code: $http_code"
          echo "Response Body: $body"

          if [ "$http_code" -ne 200 ]; then
            echo "Error: Failed to get a response from AI. HTTP Code: $http_code"
            exit 1
          fi

      # Step 8: Check Main Server Readiness
      - name: Check main server readiness
        run: |
          echo "Checking if the main server is up..."
          expected='{"message":"The server is up and running!"}'
          end=$((SECONDS+180)) # Wait up to 3 minutes
          while [ $SECONDS -lt $end ]; do
            response=$(curl -s http://localhost:8000)
            if [ "$response" = "$expected" ]; then
              echo "Main server is running!"
              exit 0
            fi
            echo "Waiting for main server..."
            sleep 5
          done
          echo "Error: Main server did not start within 3 minutes."
          exit 1

      # Step 9: Run Integration Tests
      - name: Run Python Integration Tests
        working-directory: ${{ github.workspace }}
        run: |
          python -m unittest discover -s ./test/IntegrationTests

      # Step 10: Shut Down Docker Compose
      - name: Docker-compose down
        working-directory: src/backend
        if: always()
        run: docker-compose down
