name: Docker Compose Test on PR

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the pull request code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Run Docker Compose
      - name: Run docker-compose up
        working-directory: src/backend  # Specify working directory here
        run: docker-compose up -d

      # Step 4: Test if the main server is up
      - name: Test main server with curl
        run: |
          end=$((SECONDS+120))  # Wait up to 2 minutes
          while [ $SECONDS -lt $end ]; do
            if curl -s http://localhost:8000 > /dev/null; then
              echo "Server is up!"
              exit 0
            else
              echo "Waiting for server to be up..."
              sleep 5
            fi
          done
          echo "Error: Server did not start within 2 minutes."
          exit 1
          
      # Step 5: Verify Ollama Server is Running
      - name: Check Ollama server health
        run: |
          end=$((SECONDS+180))  # Wait up to 3 minutes
          while [ $SECONDS -lt $end ]; do
            if curl -s http://localhost:11434 > /dev/null; then
              echo "Ollama server is running!"
              exit 0
            fi
            echo "Waiting for Ollama server readiness..."
            sleep 5
          done
          echo "Error: Ollama server did not start within 3 minutes."
          exit 1

      # Step 6: Run Python Integration Tests
      - name: Run Python Integration Tests
        working-directory: ${{ github.workspace }}
        run: |
          python -m unittest discover -s ./test/IntegrationTests

      # Step 7: Shut down Docker Compose (clean up)
      - name: Docker-compose down
        working-directory: src/backend  # Specify working directory here as well
        if: always()
        run: docker-compose down
