name: Docker Compose Integration Test on PR

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the pull request code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker and Docker Compose
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      # Step 3: Start Docker Compose
      - name: Start Docker Compose
        working-directory: src/backend
        run: docker-compose up -d

      # Step 4: Verify Ollama Server is Running
      - name: Check Ollama server health
        run: |
          echo "Checking if Ollama server is up..."
          end=$((SECONDS+300)) # Wait up to 5 minutes
          while [ $SECONDS -lt $end ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:11434/)
            if [ "$response" -eq 200 ]; then
              echo "Ollama server is running!"
              break
            fi
            echo "Waiting for Ollama server readiness..."
            sleep 5
          done
          if [ "$response" -ne 200 ]; then
            echo "Error: Ollama server did not start within 5 minutes. HTTP Status Code: $response"
            exit 1
          fi

      # Step 5: Wait for Ollama server to fully start
      - name: Wait for Ollama server to fully initialize
        run: |
          echo "Waiting for Ollama server to fully initialize..."
          sleep 20  # Give the container time to fully start

      # Step 6: List all running containers
      - name: List running containers
        run: docker ps

      # Step 7: Check Main Server Health
      - name: Check main server health
        run: |
          echo "Checking if the main server health endpoint is responding..."
          end=$((SECONDS+300)) # Wait up to 5 minutes
          while [ $SECONDS -lt $end ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)  # Adjust the health endpoint as necessary
            if [ "$response" -eq 200 ]; then
              echo "Main server health is OK!"
              break
            fi
            echo "Waiting for main server health..."
            sleep 5
          done
          if [ "$response" -ne 200 ]; then
            echo "Error: Main server health check failed within 5 minutes. HTTP Status Code: $response"
            exit 1
          fi

      # Step 8: Check Main Server Readiness
      - name: Check main server readiness
        run: |
          echo "Checking if the main server is up..."
          end=$((SECONDS+600)) # Wait up to 10 minutes
          while [ $SECONDS -lt $end ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000)
            if [ "$response" -eq 200 ]; then
              echo "Main server is running!"
              exit 0
            fi
            echo "Waiting for main server..."
            sleep 5
          done
          echo "Error: Main server did not start within 10 minutes."
          exit 1

      # Step 9: Check Main Server Logs
      - name: Check main server logs
        run: |
          container_id=$(docker ps -q --filter "ancestor=python:3.10-slim")  # Use the identified main server image name
          if [ -z "$container_id" ]; then
            echo "Error: Main server container not found."
            exit 1
          fi
          echo "Fetching logs for container: $container_id"
          docker logs "$container_id"

      # Step 10: Run Integration Tests
      - name: Run Python Integration Tests
        working-directory: ${{ github.workspace }}
        run: |
          python -m unittest discover -s ./test/IntegrationTests

      # Step 11: Shut Down Docker Compose
      - name: Docker-compose down
        working-directory: src/backend
        run: docker-compose down
        if: always()
