- name: Setup SSH
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
    chmod 600 ~/.ssh/id_ed25519
    ssh-keyscan github.com >> ~/.ssh/known_hosts

- name: Clone Private Repo
  run: |
    git clone git@github.com:YourUsername/YourPrivateRepo.git private-repo

- name: Secure Cleanup
  run: |
    rm -rf ~/.ssh/id_ed25519
    echo "✅ SSH key removed after use"
