name: Run Frontend Tests
on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clone Private Repo
      run: |
        git clone git@github.com:SaravanakumarR2018/primitivechatenv.git private-repo

    - name: List contents of private-repo for debugging
      run: |
        ls -la private-repo

    - name: Verify .env.local file
      run: |
        if [ -f private-repo/.env.local ]; then
          echo ".env.local file exists in private-repo"
        else
          echo ".env.local file does not exist in private-repo"
          exit 1
        fi

    - name: Move contents to src/frontend
      run: |
        cp -r private-repo/. src/frontend/

    - name: Verify .env.local file
      run: |
        if [ -f src/frontend/.env.local ]; then
          echo ".env.local file exists in src/frontend"
        else
          echo ".env.local file does not exist in src/frontend"
          exit 1
        fi

    - name: Install dependencies
      run: |
        cd src/frontend
        npm install

    - name: Build the project
      run: |
        cd src/frontend
        npm run build

    - name: Start Next.js server
      run: |
        cd src/frontend
        npm start &
        sleep 10

    - name: Wait for server to be up
      run: |
        source src/frontend/.env
        for i in {1..18}; do
          if nc -zv ${NEXT_PUBLIC_HOST:-localhost} ${NEXT_PUBLIC_PORT:-3000}; then
            echo "Server is listening on ${NEXT_PUBLIC_HOST:-localhost}:${NEXT_PUBLIC_PORT:-3000}"
            exit 0
          else
            echo "Waiting for server to be up..."
            sleep 10
          fi
        done
        echo "Server did not start within 3 minutes"
        exit 1

    - name: Install and Run Playwright tests
      run: |
        cd src/frontend
        npx playwright install
        npx playwright test

    - name: Secure Cleanup
      if: always()
      run: |
        rm -rf ~/.ssh/id_ed25519
        echo "✅ SSH key removed after use"