name: Docker Compose Test on PR

on:
  pull_request:
    branches:
      - main  # Change this to your target branch if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the pull request code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Run Docker Compose
      - name: Run docker-compose up
        working-directory: src/backend  # Specify working directory here
        env:
          PROJECT_ROOT: ${{ github.workspace }}
        run: docker-compose up -d

      # Step 4: Wait for the server to start (optional sleep to ensure the server is up)
      - name: Wait for the server
        run: sleep 10  # Adjust this if the service takes longer to start

      # Step 5: Run curl command to check if the server is working
      - name: Test server with curl
        run: curl http://0.0.0.0:8000

      # Step 6: Shut down Docker Compose (clean up)
      - name: Docker-compose down
        working-directory: src/backend  # Specify working directory here as well
        if: always()
        run: docker-compose down
